<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="SBR-DEVPQA-12" name="com.cm.qa.testcases.ContactPersonsPageTests" tests="22" failures="2" timestamp="17 Sep 2019 09:57:40 GMT" time="561.996" errors="1">
  <testcase name="verifyInvalidPersonNameTest" time="23.407" classname="com.cm.qa.testcases.ContactPersonsPageTests"/>
  <testcase name="verifyInvalidPersonNameTest" time="23.858" classname="com.cm.qa.testcases.ContactPersonsPageTests"/>
  <testcase name="verifyInvalidPersonNameTest" time="22.938" classname="com.cm.qa.testcases.ContactPersonsPageTests"/>
  <testcase name="verifyInvalidPersonNameTest" time="22.810" classname="com.cm.qa.testcases.ContactPersonsPageTests"/>
  <testcase name="verifyInvalidEmailTest" time="23.211" classname="com.cm.qa.testcases.ContactPersonsPageTests"/>
  <testcase name="verifyInvalidEmailTest" time="23.195" classname="com.cm.qa.testcases.ContactPersonsPageTests"/>
  <testcase name="verifyInvalidEmailTest" time="24.410" classname="com.cm.qa.testcases.ContactPersonsPageTests"/>
  <testcase name="verifyInvalidEmailTest" time="23.622" classname="com.cm.qa.testcases.ContactPersonsPageTests"/>
  <testcase name="verifyInvalidPhoneNumberTest" time="22.571" classname="com.cm.qa.testcases.ContactPersonsPageTests"/>
  <testcase name="verifyInvalidPhoneNumberTest" time="25.110" classname="com.cm.qa.testcases.ContactPersonsPageTests"/>
  <testcase name="verifyInvalidPhoneNumberTest" time="22.237" classname="com.cm.qa.testcases.ContactPersonsPageTests"/>
  <testcase name="verifyInvalidPhoneNumberTest" time="24.113" classname="com.cm.qa.testcases.ContactPersonsPageTests"/>
  <testcase name="addNewFunctionTest" time="24.502" classname="com.cm.qa.testcases.ContactPersonsPageTests">
    <failure type="java.lang.AssertionError" message="expected [Function successfully created
Operation Success] but found [Function successfully update
Operation Success]">
      <![CDATA[java.lang.AssertionError: expected [Function successfully created
Operation Success] but found [Function successfully update
Operation Success]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.cm.qa.testcases.ContactPersonsPageTests.addNewFunctionTest(ContactPersonsPageTests.java:81)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- addNewFunctionTest -->
  <testcase name="duplicateFunctionNameTest" time="25.381" classname="com.cm.qa.testcases.ContactPersonsPageTests">
    <failure type="java.lang.AssertionError" message="expected [CREATE: Error, Function with name CRM already exists!
Operation Success] but found [CREATE: Error, Function with name CRM already exists!
Error]">
      <![CDATA[java.lang.AssertionError: expected [CREATE: Error, Function with name CRM already exists!
Operation Success] but found [CREATE: Error, Function with name CRM already exists!
Error]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.cm.qa.testcases.ContactPersonsPageTests.duplicateFunctionNameTest(ContactPersonsPageTests.java:92)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- duplicateFunctionNameTest -->
  <testcase name="blankFunctionNameTest" time="24.138" classname="com.cm.qa.testcases.ContactPersonsPageTests"/>
  <testcase name="addContactPersonsTest" time="25.742" classname="com.cm.qa.testcases.ContactPersonsPageTests"/>
  <testcase name="addContactPersonsTest" time="32.111" classname="com.cm.qa.testcases.ContactPersonsPageTests"/>
  <testcase name="addContactPersonsTest" time="27.220" classname="com.cm.qa.testcases.ContactPersonsPageTests"/>
  <testcase name="addContactPersonsTest" time="26.799" classname="com.cm.qa.testcases.ContactPersonsPageTests"/>
  <testcase name="addContactPersonsTest" time="25.002" classname="com.cm.qa.testcases.ContactPersonsPageTests"/>
  <testcase name="editContactPersonTest" time="45.796" classname="com.cm.qa.testcases.ContactPersonsPageTests">
    <error type="org.openqa.selenium.TimeoutException" message="Expected condition failed: waiting for visibility of Proxy element for: DefaultElementLocator &#039;By.xpath: //div[contains(@class,&#039;toast-success&#039;)]&#039; (tried for 10 second(s) with 500 milliseconds interval)">
      <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of Proxy element for: DefaultElementLocator 'By.xpath: //div[contains(@class,'toast-success')]' (tried for 10 second(s) with 500 milliseconds interval)
at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:113)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:283)
at cm.cm.qa.base.TestBase.customVisibleWait(TestBase.java:65)
at com.cm.qa.utills.Utills.readSuccessMessage(Utills.java:30)
at com.cm.qa.testcases.ContactPersonsPageTests.editContactPersonTest(ContactPersonsPageTests.java:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element: //div[contains(@class,'toast-success')]
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'SBR-DEVPQA-12', ip: '10.182.106.119', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_112'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 69.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20190827005903, moz:geckodriverVersion: 0.24.0, moz:headless: false, moz:processID: 20004, moz:profile: C:\Users\subhash.bhatewera\..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: c99373ec-be7f-46d1-9384-864cfc083e56
*** Element info: {Using=xpath, value=//div[contains(@class,'toast-success')]}
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:322)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:424)
at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:314)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
at com.sun.proxy.$Proxy10.isDisplayed(Unknown Source)
at org.openqa.selenium.support.ui.ExpectedConditions.elementIfVisible(ExpectedConditions.java:315)
at org.openqa.selenium.support.ui.ExpectedConditions.access$100(ExpectedConditions.java:44)
at org.openqa.selenium.support.ui.ExpectedConditions$10.apply(ExpectedConditions.java:301)
at org.openqa.selenium.support.ui.ExpectedConditions$10.apply(ExpectedConditions.java:298)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:260)
... 28 more
]]>
    </error>
  </testcase> <!-- editContactPersonTest -->
  <testcase name="deleteContactPersonTest" time="23.823" classname="com.cm.qa.testcases.ContactPersonsPageTests"/>
</testsuite> <!-- com.cm.qa.testcases.ContactPersonsPageTests -->
